### ISSUE TITLE
Síntesis

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/actividad-3-sintesis-IsaHuerta23#2]
Síntesis

**Comment by IsaHuerta23** [comment]
[Síntesis - Elementos de Gestión de Proyectos de Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-IsaHuerta23/files/9457457/Sintesis.-.Elementos.de.Gestion.de.Proyectos.de.Software.pdf)

**Comment by salathiel1999** [comment]
18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
